/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.Equipos.jPanelListEquipo;
import Views.Equipos.jPanelNewEquipo;
import Views.Equipos.jPanelSearchEquipo;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author GUSTAVO
 */
public class formMain extends javax.swing.JFrame {

    // Constantes
    private String NOMBRE_SISTEMA= "SISTEMA DE INVENTARIO";
    // Vistas 
    private jPanelNewEquipo jpNewEquipo;
    private jPanelListEquipo jpListEquipo;
    private jPanelSearchEquipo jpSearchEquipo;
    /**
     * Creates new form formMain
     */
    public formMain(int userId) {
        
        System.out.println(userId);
        initComponents();
        setLocationRelativeTo(null);  
        setLayout(new FlowLayout());
        this.setTitle(NOMBRE_SISTEMA);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuBusquedaEquipo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Equipos");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Listar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuBusquedaEquipo.setText("Busqueda");
        menuBusquedaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBusquedaEquipoActionPerformed(evt);
            }
        });
        jMenu1.add(menuBusquedaEquipo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Oficinas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transferencia");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        closeAllPanels();
        this.setTitle("LISTA DE EQUIPOS POR DEPENDENCIA - "+ NOMBRE_SISTEMA);
        jpListEquipo = new jPanelListEquipo();
        this.add(jpListEquipo,BorderLayout.CENTER);
        
        this.pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        closeAllPanels();
        this.setTitle("NUEVO EQUIPO - "+ NOMBRE_SISTEMA);
        jpNewEquipo = new jPanelNewEquipo();
        this.add(jpNewEquipo,BorderLayout.CENTER);
        
        this.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuBusquedaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBusquedaEquipoActionPerformed
        // TODO add your handling code here:
         closeAllPanels();
        this.setTitle("BUSQUEDA DE EQUIPO - "+ NOMBRE_SISTEMA);
        jpSearchEquipo = new jPanelSearchEquipo();
        this.add(jpSearchEquipo,BorderLayout.CENTER);
        
        this.pack();
    }//GEN-LAST:event_menuBusquedaEquipoActionPerformed
    
    private void closeAllPanels(){
        try{
        this.remove(jpNewEquipo);
        this.remove(jpListEquipo);
        this.remove(jpSearchEquipo);
        }
        catch(Exception e){
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuBusquedaEquipo;
    // End of variables declaration//GEN-END:variables
}
